### ISSUE TITLE
Hierarchical Agents seem to run into pickling errors

### ISSUE THREAD

**Issue by BrianLYS** [simbianai/taskgen#6]
I'm running into this error when I run a_base_agent.py in [link to code](https://github.com/simbianai/taskgen/pull/5/files#diff-117c522789990443b632659a0064dc2ad84f8a2243f0adc0eb4c7b1c1da59852)

I'll see if I can fix this error, but putting it here just in case anyone knows how to solve already.
```
(venv) brianlim@Brians-MacBook-Pro web_browser_implementation % python a_base_agent.py
Subtask identified: Create a new instance of the Chrome driver
Calling function Create_a_new_instance_of_the_Chrome_driver with parameters {'x': 1}
> {'Driver': <selenium.webdriver.chrome.webdriver.WebDriver (session="cd41f888559c13f745f134b8ad3764a6")>}

Subtask identified: Navigate to www.example.com web page
Calling function Navigate_to_a_web_page with parameters {'url': 'http://www.example.com'}
> {'Status': 'Completed'}

Task completed successfully!

Agent output: [{'Driver': <selenium.webdriver.chrome.webdriver.WebDriver (session="cd41f888559c13f745f134b8ad3764a6")>}, {'Status': 'Completed'}]
Subtask identified: Click the screen at coordinates 100 and 200
Calling function click_screen with parameters {'x': 100, 'y': 200}
> {'Output': 'Clicked the screen at coordinates (100, 200)'}

Task completed successfully!

Agent: [{'Output': 'Clicked the screen at coordinates (100, 200)'}]
Subtask identified: Take a screenshot at 1
Calling function take_screenshot with parameters {'x': 1}
> {'Output': 'Screenshot saved at: /Users/brianlim/coding/taskgen/contrib/web_browser_implementation/screenshots/screenshot_20240317_010754.png'}

Task completed successfully!

Agent: [{'Output': 'Clicked the screen at coordinates (100, 200)'}, {'Output': 'Screenshot saved at: /Users/brianlim/coding/taskgen/contrib/web_browser_implementation/screenshots/screenshot_20240317_010754.png'}]
Subtask identified: Navigate to www.example.com
Calling function Screen Interaction Agent with parameters {'instruction': 'Navigate to www.example.com'}

### Start of Inner Agent: Screen Interaction Agent ###
Traceback (most recent call last):
  File "/Users/brianlim/coding/taskgen/contrib/web_browser_implementation/a_base_agent.py", line 22, in <module>
    output = base_agent.run(task)
  File "/Users/brianlim/coding/taskgen/venv/src/taskgen-ai/taskgen/agent.py", line 532, in run
    res = self.use_function(function_name, function_params, subtask)
  File "/Users/brianlim/coding/taskgen/venv/src/taskgen-ai/taskgen/agent.py", line 351, in use_function
    res = self.function_map[function_name](**function_params, shared_variables = self.shared_variables)
  File "/Users/brianlim/coding/taskgen/venv/src/taskgen-ai/taskgen/base.py", line 671, in __call__
    fn_output = self.external_fn(**function_kwargs)
  File "/Users/brianlim/coding/taskgen/venv/src/taskgen-ai/taskgen/agent.py", line 583, in __call__
    agent_copy = copy.deepcopy(self.agent)
  File "/Users/brianlim/.pyenv/versions/3.10.11/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/brianlim/.pyenv/versions/3.10.11/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/brianlim/.pyenv/versions/3.10.11/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/Users/brianlim/.pyenv/versions/3.10.11/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/brianlim/.pyenv/versions/3.10.11/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/Users/brianlim/.pyenv/versions/3.10.11/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/brianlim/.pyenv/versions/3.10.11/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/brianlim/.pyenv/versions/3.10.11/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/brianlim/.pyenv/versions/3.10.11/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/Users/brianlim/.pyenv/versions/3.10.11/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/brianlim/.pyenv/versions/3.10.11/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/brianlim/.pyenv/versions/3.10.11/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/brianlim/.pyenv/versions/3.10.11/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/Users/brianlim/.pyenv/versions/3.10.11/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/brianlim/.pyenv/versions/3.10.11/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/brianlim/.pyenv/versions/3.10.11/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/brianlim/.pyenv/versions/3.10.11/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/Users/brianlim/.pyenv/versions/3.10.11/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/brianlim/.pyenv/versions/3.10.11/lib/python3.10/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_thread.lock' object
```

**Comment by tanchongmin** [comment]
This should be native to the pickle implemented in the functions, and not a TaskGen error :)
